config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notifications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
  
  belongs_to :notification
end

app/models/notification.rb
class Notification < ApplicationRecord
    validates_presence_of :title
    validates_presence_of :description
    validates_presence_of :email

    has_rich_text :description
    has_many :comments, dependent: :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_notification
    before_action :authenticate_user!
    #broadcasts_to :notification

    def create
        @notification.comments.create! params.required(:comment).permit(:content,:user_id)
        redirect_to @notification
    end

    private
        def set_notification
            @notification = Notification.find(params[:notification_id])
        end 
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /notifications or /notifications.json
  def index
    @notifications_received = Notification.where(email: current_user.email).order("created_at DESC")
    @notifications_sent = Notification.where(user_id: current_user.id).order("created_at DESC")
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    email_list = notification_params['email'].split(';').uniq
    if email_list.count == 0 || notification_params['title'] == ""
      flash[:red] = "For a notification, atleast a 'Title' and an 'Email' is required."
      redirect_to '/notifications/new'
      return 
    else
      email_list.each do |email|
        single_notification = Notification.new(notification_params)
        single_notification.user_id = current_user.id
        single_notification.email = email
        single_notification.save
      end
    end
    flash[:green] = "Notification was successfully created."
    redirect_to :action => 'index'
    # TODO NotificationsMailer.recieved(@notification).deliver_later
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notification_url(@notification), green: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url, green: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:title, :description, :email)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
    <b><%= User.find(comment.user_id).email%></b>:
    <%= comment.content %>
    <i>(<%= time_tag comment.created_at, "data-local":"time-ago" %>)</i>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [ notification, Comment.new ] do |form| %>
    Add a comment: <br>
    <%= form.text_area :content, size:"20x2" %>
    <%= form.number_field :user_id, class:"form-control", value:current_user.id, type: :hidden %>
    <%= form.submit %>
<% end %>

app/views/layouts/_flash.html.erb
<%# :danger, :info, :warning, :success, :messages %>
<% flash.each do |type, msg| %>
    <% type = 'green' if type == 'notice'%>
    <div>
        <p style="color:<%= type %>"><%= msg %></p>
    </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notification Center</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= javascript_importmap_tags %>
    <style>
      body { grid-template-columns:1fr min(50rem, 90%) 1fr; text-align: center; }
      th {background: var(--accent); color:white}
    </style>
  </head>

  <body>
    <header>
      <% if current_user %>
        Logged in as<b><%= " admin" if current_user.is_admin%></b>: <i><%= current_user.email %></i>
        <%= button_to "Sign out", destroy_user_session_path, form: {style: 'display:inline-block;'}, method: :delete%>
      <% else %>
        <%= button_to "Sign up", new_user_registration_path, class:"nav-link", form: {style: 'display:inline-block;'}, :method => :get%>
        or
        <%= button_to "Login", new_user_session_path, class:"nav-link", form: {style: 'display:inline-block;'}, :method => :get %>
      <% end %>
    </header>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/notifications/_comments.html.erb
<h3>Comments</h3>

<div id="comments">
    <%= render notification.comments %>
</div>

<br>
<div>
<%= render "comments/new", notification: notification %>
</div>

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, style: "width: 100%"%>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description%>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <i> (For multiple emails, use ';' as delimiter) </i>
    <%= form.text_field :email, style: "width: 100%"%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
  <td>
    <%= User.find(notification.user_id).email%>
  </td>
  <td>
    <%= notification.email%>
  </td>
  <td>
    <%= notification.title %>
  </td>
  <td>
    <%= time_tag notification.created_at, "data-local":"time-ago" %>
  </td>
  <td>
    <% if notification.seen %>
      <%= "Read" %>
    <% else %>
      <%= "Unread" %>
    <% end %>
  </td>

app/views/notifications/_notification_table.html.erb
<div id="notifications">
  <% if notifications.count == 0 %>
    <p><i> You do not have any notifications to show here...</i></p>
  <% else %>
    <table>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Subject</th>
        <th>When</th>
        <th colspan="100%"></th>
      </tr>
    <% notifications.each do |notification| %>
      <tr>
        <%= render notification %>
        <td>
          <%= link_to "Open", notification %>
        </td>
      </tr>
    <% end %>
    <table>
  <% end %>
</div>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Show this notification", @notification %> |
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/index.html.erb
<% if current_user.is_admin %>
  <%= button_to "New notification", new_notification_path, :method => :get, form: {style: 'display:inline-block;'} %>
<% end %>

<h1>Inbox</h1>
<%= render :partial => 'notification_table', locals: {notifications: @notifications_received} %>

<% if current_user.is_admin %>
<h1>Sent</h1>
<%= render :partial => 'notification_table', locals: {notifications: @notifications_sent} %>
<% end %>

app/views/notifications/new.html.erb
<h1>New notification</h1>
<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/show.html.erb
<%= turbo_stream_from @notification %>

<%# logical to make notification seen after opening %>
<% if !@notification.seen && @notification.email==current_user.email %>
  <% new_Notification = Notification.find(@notification.id) %>
  <% @notification.seen = true %>
  <% new_Notification.seen = true %>
  <% new_Notification.save %>
<% end %>
<p style="color: green"><%= notice %></p>

<div>
  <%= button_to "Back to notifications", notifications_path, :method => :get, form: {style: 'display:inline-block;'}%>
  <% if @notification.user_id == current_user.id %>
    <%= button_to "Edit this notification", edit_notification_path(@notification), :method => :get, form: {style: 'display:inline-block;'}%>
  <% end %>
</div>

<div>
  <h3>Notification</h3>
  <table>
      <tr>
        <%= render @notification %>
        <% if current_user.is_admin && (current_user.id == @notification.email || @notification.id) %>
          <td> <%= button_to "Delete", @notification, method: :delete %> </td>
        <% end %>
      </tr>
      <tr>
        <td colspan="100%"> <%= @notification.description%> </td>
      </tr>
  </table>
</div>

<div>
<%= render "notifications/comments", notification:@notification%>
<div>